import React, { createContext, useContext, useState, useEffect } from 'react';

const dictionary = {
  en: {
    settings: 'Settings', personalize: 'Personalize your StudyFlow experience', personal: 'Personal', notify: 'Notify', sync: 'Sync', theme: 'Theme', privacy: 'Privacy', account: 'Account', uploadPic: 'Upload your picture here', firstName: 'First Name', lastName: 'Last Name', email: 'Email', phone: 'Phone', dob: 'Date of Birth', timezone: 'Timezone', institution: 'Institution', major: 'Major', gradYear: 'Graduation Year', studentId: 'Student ID', bio: 'Bio', notifications: 'Notifications', deadlineNotif: 'Deadline Notifications', missedTask: 'Missed Task Alerts', motivational: 'Motivational Messages', syncBtn: 'Manual Sync', lastSynced: 'Last synced: just now', themeTab: 'Theme', light: 'Light', dark: 'Dark', system: 'System', accessibility: 'Accessibility', fontSize: 'Font Size', small: 'Small', medium: 'Medium', large: 'Large', contrast: 'Contrast', normal: 'Normal', high: 'High', language: 'Language', privacyTab: 'Privacy', changePassword: 'Change Password', accountTab: 'Account', deleteAccount: 'Delete Account', signOut: 'Sign Out', deleteConfirm: 'Are you sure you want to delete your account? This action cannot be undone.', yesDelete: 'Yes, Delete', cancel: 'Cancel', welcomeBack: 'Welcome back!', readyToCrush: 'Ready to crush your study goals today?', studyHours: 'Study Hours', hours: 'hrs', loadingDashboard: 'Loading dashboard...', startFocusSession: 'Start Focus Session', setAvailability: 'Set Availability', viewSubjects: 'View Subjects', addAssignment: 'Add Assignment', streak: 'Streak', days: 'days', deadlines: 'Deadlines', quickActions: 'Quick Actions', recentTasks: 'Recent Tasks', due: 'Due', aiAssistant: 'AI Assistant', askMeAnything: 'Ask me anything...', send: 'Send', aiWelcome: "Hi! I am StudyFlow's AI Assistant. I can help you with your computer science studies, including: • Network concepts and protocols • Database design and SQL queries • Operating System topics • Software Engineering methodologies What can I help you with today?",
    aiSampleQ: "I'm having trouble understanding database normalization. Can you help?",
    aiTyping: "AI is typing...",
    aiNormExplain: "Database normalization can be tricky! It is a process of organizing a database to reduce redundancy and improve data integrity. Let me break it down... First Normal Form (1NF): Each table must contain a single value, and each record needs to be unique. No repeating groups of columns. Second Normal Form (2NF): The table must be in 1NF, and all non-key attributes must depend on the entire primary key. Third Normal Form (3NF): The table must be in 2NF, and all attributes must depend directly on the primary key, not on other non-key attributes. Boyce-Codd Normal Form (BCNF): A stricter version of 3NF that addresses certain anomalies not handled by 3NF. Would you like me to provide a specific example of normalizing a database table?",
    tasksDone: 'Tasks Done',
    dashboard: 'Dashboard',
    assignments: 'Assignments',
    importFromMoodle: 'Import from Moodle',
    analyticsGrade: 'Analytics/Grade',
    rewardsAndStreak: 'Rewards and Streak',
    focusMode: 'Focus Mode',
    session: 'Session',
    quickDuration: 'Quick Duration',
    min: 'min',
    start: 'Start',
    pause: 'Pause',
    reset: 'Reset',
    break: 'Break',
    completedSessions: 'Completed Sessions',
    enableNotifications: 'Enable Notifications',
    howPomodoroWorks: 'How Pomodoro Works',
    workForDuration: 'Work for the set duration (e.g., 25 minutes).',
    takeShortBreak: 'Take a short break (e.g., 5 minutes).',
    afterSessionsLongBreak: 'After several sessions, take a longer break.',
    repeatStayFocused: 'Repeat and stay focused!',
    subjects: 'Subjects',
    calendar: 'Calendar',
    progress: 'Progress',
    help: 'Help',
    user: 'User',
    student: 'Student',
    notificationCenter: 'Notification Center',
    manageAlerts: 'Manage how and when you receive alerts',
    taskDashboard: 'Task Dashboard',
    showDeadlineAlert: 'Show Deadline Alert',
    showMissedTaskAlert: 'Show Missed Task Alert',
    showMotivationalAlert: 'Show Motivational Alert',
    deadlineAlert: 'Deadline Alert!',
    missedTaskAlert: 'Missed Task Alert!',
    motivationalAlert: 'Motivational Alert!',
    notificationSettings: 'Notification Settings',
    deadlineNotifications: 'Deadline Notifications',
    missedTaskAlerts: 'Missed Task Alerts',
    motivationalMessages: 'Motivational Messages',
    notificationStyle: 'Notification Style',
    popup: 'Pop-up',
    banner: 'Banner',
    both: 'Both',
    selectDay: 'Select Day',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    startTime: 'Start Time',
    endTime: 'End Time',
    best: 'Best',
    update: 'Update',
    add: 'Add',
    loading: 'Loading...',
    noAvailabilitySet: 'No availability set.',
    edit: 'Edit',
    delete: 'Delete',
    'Failed to load availability.': 'Failed to load availability.',
    'Failed to save.': 'Failed to save.',
    'Failed to delete.': 'Failed to delete.',
    logIn: 'Log In',
    signUp: 'Sign Up',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    orContinueWith: 'or continue with',
    connectWithGoogle: 'Connect with Google',
    connectToMoodle: 'Connect to Moodle',
    aiAssistantTitle: 'StudyFlow AI Assistant',
    aiAssistantDesc: 'Get 24/7 academic support with our AI tutor. Ask questions, get study tips, and receive personalized learning recommendations.',
    noAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    registrationDesc: 'Your complete academic companion. Plan, track, and excel in your studies.',
    computerEducation: 'Computer Education',
    newToStudyFlow: 'New to StudyFlow? Sign up to:',
    createPersonalizedSchedules: 'Create personalized study schedules',
    trackAssignmentsDeadlines: 'Track assignments and deadlines',
    connectWithClassmates: 'Connect with classmates',
    accessCourseMaterials: 'Access course materials',
    fullName: 'Full Name',
    academicYear: 'Academic Year',
    register: 'Register',
    helpFaq: 'Help & FAQ',
    frequentlyAskedQuestions: 'Frequently Asked Questions',
    askAQuestion: 'Ask a Question',
    typeYourQuestion: 'Type your question...',
    ask: 'Ask',
    yourQuestions: 'Your Questions',
    q: 'Q',
    a: 'A',
    faqAddSubjectQ: 'How do I add a new subject?',
    faqAddSubjectA: 'Go to the Subjects page and click the "+ Add Subject" button.',
    faqScheduleTaskQ: 'How can I schedule a task on the calendar?',
    faqScheduleTaskA: 'Click an empty cell in the calendar grid and select a task from the unscheduled list.',
    faqUpdateProgressQ: 'How do I update my progress?',
    faqUpdateProgressA: 'Go to the Progress page and use the slider to update your progress for each subject.',
    faqMobileQ: 'Can I use StudyFlow on my phone?',
    faqMobileA: 'Yes! StudyFlow is mobile-friendly and works in your browser.',
    'Login successful! Welcome back.': 'Login successful! Welcome back.',
    'Login failed: No token received.': 'Login failed: No token received.',
    'Login failed.': 'Login failed.',
    'Registration successful! You can now log in.': 'Registration successful! You can now log in.',
    'Registration failed.': 'Registration failed.',
    'Error connecting to server.': 'Error connecting to server.',
    title: 'Title',
    subject: 'Subject',
    highPriority: 'High Priority',
    mediumPriority: 'Medium Priority',
    lowPriority: 'Low Priority',
    adding: 'Adding...',
    loadingAssignments: 'Loading assignments...',
    noAssignments: 'No assignments found.',
    markIncomplete: 'Mark Incomplete',
    markComplete: 'Mark Complete',
    incomplete: 'Incomplete',
    complete: 'Complete',
    noDueDate: 'No due date',
    priority: 'Priority',
    rewardsStreakSystem: 'Rewards & Streak System',
    trackProgressEarnRewards: 'Track your progress and earn rewards',
    level: 'level',
    knowledgeSeeker: 'knowledge seeker',
    today: 'today',
    bonusClaimed: 'Bonus Claimed',
    claimDailyBonus: 'Claim Daily Bonus',
    currentStreak: 'Current Streak',
    youreOnFire: "You're on fire!",
    badgesEarned: 'Badges Earned',
    viewAllBadges: 'View All Badges',
    dailyLoginStreak: 'Daily Login Streak',
    reach8DaysUnlock: 'Reach 8 days to unlock!',
    Consistency: 'Consistency',
    'Top Scorer': 'Top Scorer',
    'Streak Master': 'Streak Master',
    'Quiz Whiz': 'Quiz Whiz',
    gradesPerformanceAnalytics: 'Grades & Performance Analytics',
    exportReport: 'Export Report',
    filter: 'Filter',
    trackAcademicProgress: 'Track your academic progress and identify areas for improvement',
    gradeTrends: 'Grade Trends',
    weeklyMonthlySemester: 'Weekly, Monthly, Semester',
    missedTasks: 'Missed Tasks',
    bySubjectWeekType: 'By Subject, By Week, By Type',
    importFromMoodleDesc: 'Import your assignments and deadlines from Moodle to StudyFlow',
    courseLink: 'Course Link',
    apiToken: 'API Token',
    calendarFile: 'Calendar File',
    pasteMoodleCourseLink: 'Paste Moodle Course Link',
    rememberMoodleCredentials: 'Remember my Moodle credentials for future imports',
    fetchAssignments: 'Fetch Assignments',
    fetching: 'Fetching...',
    assignmentsFound: 'Assignments Found:',
    enterApiToken: 'Enter API Token',
    pasteApiToken: 'Paste your Moodle API token here',
    uploadCalendarFile: 'Upload Calendar File',
    needHelp: 'Need Help?',
    helpMoodleLogin: "Make sure you're logged into your Moodle account before copying the course link",
    helpApiToken: 'For API token import, you\'ll need to request a token from your Moodle administrator',
    helpCalendarExport: 'Calendar files can be exported from your Moodle calendar view (look for "Export Calendar" option)',
    informationtechnology: 'Information Technology',
    addSubject: 'Add Subject',
    unscheduledTasks: 'Unscheduled Tasks',
    noUnscheduledTasks: 'No unscheduled tasks',
    weekRange: 'Week Range',
    week: 'Week',
    month: 'Month',
    timeBlocked: 'Time Blocked',
    flexible: 'Flexible',
    sun: 'Sun',
    mon: 'Mon',
    tue: 'Tue',
    wed: 'Wed',
    thu: 'Thu',
    fri: 'Fri',
    sat: 'Sat',
    progressOverview: 'Progress Overview',
    overallProgress: 'Overall Progress',
    assignmentAddForbidden: 'You are not authorized. Please log in again.',
    assignmentAddError: 'Failed to add assignment. Please try again.',
  },
  ar: {
    settings: 'الإعدادات', personalize: 'خصص تجربتك في StudyFlow', personal: 'شخصي', notify: 'الإشعارات', sync: 'مزامنة', theme: 'المظهر', privacy: 'الخصوصية', account: 'الحساب', uploadPic: 'ارفع صورتك هنا', firstName: 'الاسم الأول', lastName: 'اسم العائلة', email: 'البريد الإلكتروني', phone: 'الهاتف', dob: 'تاريخ الميلاد', timezone: 'المنطقة الزمنية', institution: 'المؤسسة', major: 'التخصص', gradYear: 'سنة التخرج', studentId: 'رقم الطالب', bio: 'نبذة', notifications: 'الإشعارات', deadlineNotif: 'إشعارات المواعيد النهائية', missedTask: 'تنبيهات المهام الفائتة', motivational: 'رسائل تحفيزية', syncBtn: 'مزامنة يدوية', lastSynced: 'آخر مزامنة: الآن', themeTab: 'المظهر', light: 'فاتح', dark: 'داكن', system: 'النظام', accessibility: 'إمكانية الوصول', fontSize: 'حجم الخط', small: 'صغير', medium: 'متوسط', large: 'كبير', contrast: 'التباين', normal: 'عادي', high: 'مرتفع', language: 'اللغة', privacyTab: 'الخصوصية', changePassword: 'تغيير كلمة المرور', accountTab: 'الحساب', deleteAccount: 'حذف الحساب', signOut: 'تسجيل الخروج', deleteConfirm: 'هل أنت متأكد أنك تريد حذف حسابك؟ لا يمكن التراجع عن هذا الإجراء.', yesDelete: 'نعم، احذف', cancel: 'إلغاء', welcomeBack: 'مرحبًا بعودتك!', readyToCrush: 'هل أنت مستعد لتحقيق أهدافك الدراسية اليوم؟', studyHours: 'ساعات الدراسة', hours: 'س', loadingDashboard: 'جاري تحميل لوحة التحكم...', startFocusSession: 'ابدأ جلسة تركيز', setAvailability: 'تعيين التوفر', viewSubjects: 'عرض المواد', addAssignment: 'إضافة مهمة', streak: 'سلسلة الإنجاز', days: 'يوم', deadlines: 'المواعيد النهائية', quickActions: 'إجراءات سريعة', recentTasks: 'المهام الأخيرة', due: 'تاريخ الاستحقاق', aiAssistant: 'مساعد الذكاء الاصطناعي', askMeAnything: 'اسألني أي شيء...', send: 'إرسال', aiWelcome: "مرحبًا! أنا مساعد الذكاء الاصطناعي في StudyFlow. يمكنني مساعدتك في دراستك لعلوم الحاسب، بما في ذلك: • مفاهيم الشبكات وبروتوكولاتها • تصميم قواعد البيانات واستعلامات SQL • مواضيع أنظمة التشغيل • منهجيات هندسة البرمجيات. كيف يمكنني مساعدتك اليوم؟",
    aiSampleQ: "أواجه صعوبة في فهم تسوية قواعد البيانات. هل يمكنك المساعدة؟",
    aiTyping: "المساعد يكتب...",
    aiNormExplain: "تسوية قواعد البيانات قد تكون صعبة! هي عملية تنظيم قاعدة البيانات لتقليل التكرار وتحسين تكامل البيانات. دعني أشرح... النموذج الأول (1NF): يجب أن يحتوي كل جدول على قيمة واحدة، ويجب أن يكون كل سجل فريدًا. لا توجد مجموعات أعمدة متكررة. النموذج الثاني (2NF): يجب أن يكون الجدول في 1NF، ويجب أن تعتمد جميع السمات غير الرئيسية على المفتاح الأساسي بالكامل. النموذج الثالث (3NF): يجب أن يكون الجدول في 2NF، ويجب أن تعتمد جميع السمات مباشرة على المفتاح الأساسي، وليس على سمات غير رئيسية أخرى. نموذج بويز-كود (BCNF): نسخة أكثر صرامة من 3NF تعالج بعض الحالات الخاصة. هل ترغب في مثال عملي؟",
    tasksDone: 'المهام المنجزة',
    dashboard: 'لوحة التحكم',
    assignments: 'الواجبات',
    importFromMoodle: 'استيراد من مودل',
    analyticsGrade: 'التحليلات/الدرجات',
    rewardsAndStreak: 'المكافآت والسلسلة',
    focusMode: 'وضع التركيز',
    session: 'الجلسة',
    quickDuration: 'مدة سريعة',
    min: 'دقيقة',
    start: 'ابدأ',
    pause: 'إيقاف مؤقت',
    reset: 'إعادة ضبط',
    break: 'استراحة',
    completedSessions: 'الجلسات المكتملة',
    enableNotifications: 'تفعيل الإشعارات',
    howPomodoroWorks: 'كيف يعمل بومودورو',
    workForDuration: 'اعمل لمدة محددة (مثلاً 25 دقيقة).',
    takeShortBreak: 'خذ استراحة قصيرة (مثلاً 5 دقائق).',
    afterSessionsLongBreak: 'بعد عدة جلسات، خذ استراحة أطول.',
    repeatStayFocused: 'كرر وابقَ مركزًا!',
    subjects: 'المواد',
    calendar: 'التقويم',
    progress: 'التقدم',
    help: 'مساعدة',
    user: 'المستخدم',
    student: 'طالب',
    notificationCenter: 'مركز الإشعارات',
    manageAlerts: 'إدارة كيفية ووقت تلقي التنبيهات',
    taskDashboard: 'لوحة المهام',
    showDeadlineAlert: 'عرض تنبيه الموعد النهائي',
    showMissedTaskAlert: 'عرض تنبيه المهمة الفائتة',
    showMotivationalAlert: 'عرض تنبيه تحفيزي',
    deadlineAlert: 'تنبيه الموعد النهائي!',
    missedTaskAlert: 'تنبيه المهمة الفائتة!',
    motivationalAlert: 'تنبيه تحفيزي!',
    notificationSettings: 'إعدادات الإشعارات',
    deadlineNotifications: 'إشعارات المواعيد النهائية',
    missedTaskAlerts: 'تنبيهات المهام الفائتة',
    motivationalMessages: 'رسائل تحفيزية',
    notificationStyle: 'نمط الإشعار',
    popup: 'نافذة منبثقة',
    banner: 'شريط',
    both: 'كلاهما',
    selectDay: 'اختر اليوم',
    monday: 'الاثنين',
    tuesday: 'الثلاثاء',
    wednesday: 'الأربعاء',
    thursday: 'الخميس',
    friday: 'الجمعة',
    startTime: 'وقت البدء',
    endTime: 'وقت الانتهاء',
    best: 'الأفضل',
    update: 'تحديث',
    add: 'إضافة',
    loading: 'جارٍ التحميل...',
    noAvailabilitySet: 'لم يتم تعيين أي توفر.',
    edit: 'تعديل',
    delete: 'حذف',
    'Failed to load availability.': 'فشل في تحميل التوفر.',
    'Failed to save.': 'فشل في الحفظ.',
    'Failed to delete.': 'فشل في الحذف.',
    logIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    password: 'كلمة المرور',
    rememberMe: 'تذكرني',
    forgotPassword: 'نسيت كلمة المرور؟',
    orContinueWith: 'أو تابع باستخدام',
    connectWithGoogle: 'الاتصال بجوجل',
    connectToMoodle: 'الاتصال بمودل',
    aiAssistantTitle: 'مساعد StudyFlow الذكي',
    aiAssistantDesc: 'احصل على دعم أكاديمي على مدار الساعة مع معلم الذكاء الاصطناعي. اطرح الأسئلة، واحصل على نصائح دراسية، وتلق توصيات تعليمية مخصصة.',
    noAccount: 'ليس لديك حساب؟',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    registrationDesc: 'رفيقك الأكاديمي الكامل. خطط، وتتبع، وتفوق في دراستك.',
    computerEducation: 'تعليم الحاسوب',
    newToStudyFlow: 'جديد على StudyFlow؟ سجل لتحصل على:',
    createPersonalizedSchedules: 'أنشئ جداول دراسية مخصصة',
    trackAssignmentsDeadlines: 'تتبع الواجبات والمواعيد النهائية',
    connectWithClassmates: 'تواصل مع زملاء الدراسة',
    accessCourseMaterials: 'الوصول إلى مواد الدورة',
    fullName: 'الاسم الكامل',
    academicYear: 'السنة الأكاديمية',
    register: 'تسجيل',
    helpFaq: 'المساعدة والأسئلة الشائعة',
    frequentlyAskedQuestions: 'الأسئلة الشائعة',
    askAQuestion: 'اطرح سؤالاً',
    typeYourQuestion: 'اكتب سؤالك...',
    ask: 'اسأل',
    yourQuestions: 'أسئلتك',
    q: 'س',
    a: 'ج',
    faqAddSubjectQ: 'كيف أضيف مادة جديدة؟',
    faqAddSubjectA: 'انتقل إلى صفحة المواد واضغط على زر "+ إضافة مادة".',
    faqScheduleTaskQ: 'كيف يمكنني جدولة مهمة في التقويم؟',
    faqScheduleTaskA: 'انقر على خلية فارغة في شبكة التقويم وحدد مهمة من قائمة غير المجدولة.',
    faqUpdateProgressQ: 'كيف أقوم بتحديث تقدمي؟',
    faqUpdateProgressA: 'انتقل إلى صفحة التقدم واستخدم شريط التمرير لتحديث تقدمك لكل مادة.',
    faqMobileQ: 'هل يمكنني استخدام StudyFlow على هاتفي؟',
    faqMobileA: 'نعم! StudyFlow متوافق مع الجوال ويعمل في متصفحك.',
    'Login successful! Welcome back.': 'تم تسجيل الدخول بنجاح! مرحبًا بعودتك.',
    'Login failed: No token received.': 'فشل تسجيل الدخول: لم يتم استلام رمز.',
    'Login failed.': 'فشل تسجيل الدخول.',
    'Registration successful! You can now log in.': 'تم التسجيل بنجاح! يمكنك الآن تسجيل الدخول.',
    'Registration failed.': 'فشل التسجيل.',
    'Error connecting to server.': 'حدث خطأ أثناء الاتصال بالخادم.',
    title: 'العنوان',
    subject: 'المادة',
    highPriority: 'أولوية عالية',
    mediumPriority: 'أولوية متوسطة',
    lowPriority: 'أولوية منخفضة',
    adding: 'جاري الإضافة...',
    loadingAssignments: 'جاري تحميل الواجبات...',
    noAssignments: 'لا توجد واجبات.',
    markIncomplete: 'وضع كغير مكتمل',
    markComplete: 'وضع كمكتمل',
    incomplete: 'غير مكتمل',
    complete: 'مكتمل',
    noDueDate: 'لا يوجد تاريخ استحقاق',
    priority: 'الأولوية',
    rewardsStreakSystem: 'نظام المكافآت والسلسلة',
    trackProgressEarnRewards: 'تتبع تقدمك واحصل على المكافآت',
    level: 'المستوى',
    knowledgeSeeker: 'باحث عن المعرفة',
    today: 'اليوم',
    bonusClaimed: 'تم استلام المكافأة',
    claimDailyBonus: 'احصل على مكافأة يومية',
    currentStreak: 'سلسلة الإنجاز الحالية',
    youreOnFire: 'أنت رائع!',
    badgesEarned: 'الشارات المكتسبة',
    viewAllBadges: 'عرض كل الشارات',
    dailyLoginStreak: 'سلسلة تسجيل الدخول اليومية',
    reach8DaysUnlock: 'عند الوصول إلى 8 أيام سيتم الفتح!',
    Consistency: 'الاستمرارية',
    'Top Scorer': 'الأعلى نقاطًا',
    'Streak Master': 'سيد السلسلة',
    'Quiz Whiz': 'عبقري الاختبارات',
    gradesPerformanceAnalytics: 'تحليلات الدرجات والأداء',
    exportReport: 'تصدير التقرير',
    filter: 'تصفية',
    trackAcademicProgress: 'تتبع تقدمك الأكاديمي وحدد مجالات التحسين',
    gradeTrends: 'اتجاهات الدرجات',
    weeklyMonthlySemester: 'أسبوعي، شهري، فصلي',
    missedTasks: 'المهام الفائتة',
    bySubjectWeekType: 'حسب المادة، حسب الأسبوع، حسب النوع',
    importFromMoodleDesc: 'استورد واجباتك ومواعيدك النهائية من مودل إلى StudyFlow',
    courseLink: 'رابط المقرر',
    apiToken: 'رمز API',
    calendarFile: 'ملف التقويم',
    pasteMoodleCourseLink: 'الصق رابط مقرر مودل',
    rememberMoodleCredentials: 'تذكر بيانات اعتمادي في مودل للاستيراد مستقبلاً',
    fetchAssignments: 'جلب الواجبات',
    fetching: 'جاري الجلب...',
    assignmentsFound: 'الواجبات التي تم العثور عليها:',
    enterApiToken: 'أدخل رمز API',
    pasteApiToken: 'الصق رمز API الخاص بمودل هنا',
    uploadCalendarFile: 'رفع ملف التقويم',
    needHelp: 'تحتاج مساعدة؟',
    helpMoodleLogin: 'تأكد من تسجيل الدخول إلى حسابك في مودل قبل نسخ الرابط',
    helpApiToken: 'لاستيراد رمز API، ستحتاج لطلب رمز من مسؤول مودل الخاص بك',
    helpCalendarExport: 'يمكن تصدير ملفات التقويم من عرض تقويم مودل (ابحث عن خيار "تصدير التقويم")',
    informationtechnology: 'تقنية المعلومات',
    addSubject: 'إضافة مادة',
    unscheduledTasks: 'المهام غير المجدولة',
    noUnscheduledTasks: 'لا توجد مهام غير مجدولة',
    weekRange: 'نطاق الأسبوع',
    week: 'أسبوع',
    month: 'شهر',
    timeBlocked: 'مجدول بالوقت',
    flexible: 'مرن',
    sun: 'الأحد',
    mon: 'الاثنين',
    tue: 'الثلاثاء',
    wed: 'الأربعاء',
    thu: 'الخميس',
    fri: 'الجمعة',
    sat: 'السبت',
    progressOverview: 'نظرة عامة على التقدم',
    overallProgress: 'إجمالي التقدم',
    assignmentAddForbidden: 'غير مصرح لك. يرجى تسجيل الدخول مرة أخرى.',
    assignmentAddError: 'فشل في إضافة الواجب. يرجى المحاولة مرة أخرى.',
  }
};

const SettingsContext = createContext();

export function SettingsProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('language') || 'en');
  const [fontSize, setFontSize] = useState(() => localStorage.getItem('fontSize') || 'medium');
  const [contrast, setContrast] = useState(() => localStorage.getItem('contrast') || 'normal');

  useEffect(() => { localStorage.setItem('language', language); }, [language]);
  useEffect(() => { localStorage.setItem('fontSize', fontSize); }, [fontSize]);
  useEffect(() => { localStorage.setItem('contrast', contrast); }, [contrast]);

  useEffect(() => {
    document.body.classList.remove('font-small', 'font-medium', 'font-large');
    document.body.classList.add(`font-${fontSize}`);
  }, [fontSize]);
  useEffect(() => {
    document.body.classList.remove('high-contrast');
    if (contrast === 'high') document.body.classList.add('high-contrast');
  }, [contrast]);

  const t = (key) => dictionary[language][key] || key;

  return (
    <SettingsContext.Provider value={{ language, setLanguage, fontSize, setFontSize, contrast, setContrast, t }}>
      {children}
    </SettingsContext.Provider>
  );
}

export function useSettings() {
  return useContext(SettingsContext);
} 